"""
Management command to seed the database with target questions, badges, and admin user.
Usage: python manage.py seed_questions
"""
from django.core.management.base import BaseCommand
from quiz.models import Question
from leaderboard.models import Badge
from accounts.models import User

# List of 130 question templates. Each will be seeded for 3 user types
# (130 * 3 = 390 total questions in the DB).
TEMPLATES = [
    # ===== PHISHING (35 templates) =====
    {
        "question_text": "You receive an email from 'support@amaz0n.com' asking you to verify your password. What is the safest action?",
        "option_a": "Click the link immediately to prevent account suspension.",
        "option_b": "Ignore the email and navigate directly to amazon.com in your browser.",
        "option_c": "Reply to the sender with your login details to confirm.",
        "option_d": "Forward the email to your entire contact list.",
        "correct_answer": "B",
        "explanation": "The domain uses 'amaz0n' (with a zero) instead of 'amazon'. This is typosquatting, a common phishing tactic. Always check accounts via official bookmarks or URLs.",
        "category": "phishing",
    },
    {
        "question_text": "What is the defining characteristic of a 'smishing' attack?",
        "option_a": "It uses fraudulent voice calls to steal financial data.",
        "option_b": "It involves malicious code hidden inside image metadata.",
        "option_c": "It uses SMS or text messages to distribute phishing links.",
        "option_d": "It targets high-level executives via social media networks.",
        "correct_answer": "C",
        "explanation": "Smishing combines SMS (Short Message Service) and phishing. It delivers fraudulent links directly to mobile phone messaging apps.",
        "category": "phishing",
    },
    {
        "question_text": "What is 'vishing'?",
        "option_a": "Phishing attempts carried out over telephone calls or voice messages.",
        "option_b": "A technique to intercept wireless network traffic.",
        "option_c": "Sending fraudulent emails containing fake video links.",
        "option_d": "Malware that displays video ads on your computer screen.",
        "correct_answer": "A",
        "explanation": "Vishing stands for Voice Phishing. Attackers use phone calls (often spoofing trusted numbers) to steal PINs, card numbers, or personal info.",
        "category": "phishing",
    },
    {
        "question_text": "How does 'spear phishing' differ from generic phishing?",
        "option_a": "It only targets government networks and high-security systems.",
        "option_b": "It is highly customized and targets specific individuals or organizations.",
        "option_c": "It uses automated tools to target millions of random users at once.",
        "option_d": "It relies entirely on hardware keyloggers to capture keystrokes.",
        "correct_answer": "B",
        "explanation": "Generic phishing uses a broad net, sending emails to millions. Spear phishing is highly targeted and researched, using the victim's name or background to increase success rates.",
        "category": "phishing",
    },
    {
        "question_text": "What does a 'whaling' attack specifically target?",
        "option_a": "Entry-level employees and remote contractors.",
        "option_b": "Smart contracts and cryptocurrency exchanges.",
        "option_c": "High-profile executives like CEOs, CFOs, or government leaders.",
        "option_d": "Local databases and offline backups.",
        "correct_answer": "C",
        "explanation": "Whaling is a sub-category of spear phishing targeting the 'big fish'—high-level executives who hold access to sensitive company funds or proprietary intellectual property.",
        "category": "phishing",
    },
    {
        "question_text": "An email warns you that your bank account will be suspended in 2 hours unless you click a link. What social engineering tactic is this?",
        "option_a": "Authority",
        "option_b": "Urgency",
        "option_c": "Scarcity",
        "option_d": "Consensus",
        "correct_answer": "B",
        "explanation": "Urgency is used to panic the victim into bypass standard validation checks. Reputable organizations rarely demand urgent action under immediate threat of closure.",
        "category": "phishing",
    },
    {
        "question_text": "What is the purpose of 'pretexting' in social engineering?",
        "option_a": "Encrypting local hard drives before demanding ransom.",
        "option_b": "Creating a fabricated scenario (pretext) to convince victims to reveal information.",
        "option_c": "Using automated scripts to test weak passwords on login forms.",
        "option_d": "Hiding malicious payloads within harmless documents.",
        "correct_answer": "B",
        "explanation": "Pretexting is the act of creating an invented scenario (the pretext) where the attacker pretends to be a bank auditor, IT technician, or customer service representative to establish trust.",
        "category": "phishing",
    },
    {
        "question_text": "A coworker receives a USB drive in the mail labeled 'Confidential Q4 Salary Data' and plugs it in. This is an example of:",
        "option_a": "Tailgating",
        "option_b": "Baiting",
        "option_c": "Watering Hole attack",
        "option_d": "Pharming",
        "correct_answer": "B",
        "explanation": "Baiting relies on curiosity or greed. Leaving malware-laden USB drives, CDs, or download links where victims will find and run them is a classic baiting method.",
        "category": "phishing",
    },
    {
        "question_text": "What does 'pharming' involve?",
        "option_a": "Sending high volumes of junk email to crash servers.",
        "option_b": "Redirecting users to fraudulent websites by manipulating DNS or local host files.",
        "option_c": "Stealing password databases using SQL injection attacks.",
        "option_d": "Physical theft of office servers and workstations.",
        "correct_answer": "B",
        "explanation": "Pharming redirects users to a fake website even if they typed the correct address in their browser, typically by hijacking DNS settings or modifying host records.",
        "category": "phishing",
    },
    {
        "question_text": "Which of the following is a physical social engineering attack where an unauthorized person follows an employee into a secure area?",
        "option_a": "Piggybacking / Tailgating",
        "option_b": "Shoulder Surfing",
        "option_c": "Baiting",
        "option_d": "Phishing",
        "correct_answer": "A",
        "explanation": "Tailgating (or piggybacking) occurs when an unauthorized person physically follows a authorized person into a restricted access building or room.",
        "category": "phishing",
    },
    {
        "question_text": "An email sender's address displays 'billing@paypal-support-portal.com'. What should you suspect?",
        "option_a": "It is a legitimate support address because it contains the word 'paypal'.",
        "option_b": "It is a spoofed domain designed to impersonate PayPal support.",
        "option_c": "It is highly secure because it has two hyphens.",
        "option_d": "It is a private banking server owned by the government.",
        "correct_answer": "B",
        "explanation": "Phishers register look-alike domain names containing popular brand names (e.g. paypal-support-portal.com) to deceive recipients into believing the mail is authentic.",
        "category": "phishing",
    },
    {
        "question_text": "Which of the following describes 'clone phishing'?",
        "option_a": "Copying an existing legitimate email and replacing its link or attachment with a malicious one.",
        "option_b": "Cloning a physical access card to enter a secure data center.",
        "option_c": "Sending the same email template to thousands of recipients simultaneously.",
        "option_d": "Impersonating multiple customer support representatives in online chatrooms.",
        "correct_answer": "A",
        "explanation": "Clone phishing takes a previously delivered email, duplicates its content, and replaces links or attachments with malicious files, sending it from a spoofed address that looks like the original.",
        "category": "phishing",
    },
    {
        "question_text": "What does a 'watering hole' attack target?",
        "option_a": "Random consumers globally using general spam lists.",
        "option_b": "Websites frequently visited by a specific target group to compromise their computers.",
        "option_c": "Offline industrial control systems and water treatment plants.",
        "option_d": "Shared cloud infrastructure during off-peak hours.",
        "correct_answer": "B",
        "explanation": "In a watering hole attack, the attacker identifies websites a particular group (like employees of a target company) frequently visits, infects one of those sites, and uses it to distribute malware.",
        "category": "phishing",
    },
    {
        "question_text": "What is 'shoulder surfing'?",
        "option_a": "Hacking into wireless routers at beach resorts.",
        "option_b": "Directly observing someone's screen or keyboard to capture passwords or PINs.",
        "option_c": "Reading old deleted emails from public network drives.",
        "option_d": "Using electromagnetic fields to steal RFID card data.",
        "correct_answer": "B",
        "explanation": "Shoulder surfing involves looking over a person's shoulder to spy on their screen or keystrokes while they type credentials or PINs at ATMs, phones, or PCs.",
        "category": "phishing",
    },
    {
        "question_text": "Which of the following is the most secure way to check if an account alert email is real?",
        "option_a": "Reply directly to the email requesting verification.",
        "option_b": "Click the link in the email and see if it looks secure.",
        "option_c": "Open your web browser and go directly to the verified official site via a known URL.",
        "option_d": "Search for the sender's email address on Google and click the first result.",
        "correct_answer": "C",
        "explanation": "Never trust links inside suspicious emails. Open a clean browser window, type the official domain yourself, and log in to inspect any notifications.",
        "category": "phishing",
    },
    {
        "question_text": "If you suspect an email at work is a phishing attempt, what is your best course of action?",
        "option_a": "Delete it and do nothing.",
        "option_b": "Forward it to your colleagues to ask their opinion.",
        "option_c": "Report it directly to your organization's IT security team or use the official report button.",
        "option_d": "Reply to the attacker telling them that you caught them.",
        "correct_answer": "C",
        "explanation": "Reporting phishing allows the IT department to block the sender domain-wide, protecting coworkers who might otherwise fall victim.",
        "category": "phishing",
    },
    {
        "question_text": "Which security standard helps prevent email spoofing by verifying the sender's IP address against DNS records?",
        "option_a": "SSL/TLS",
        "option_b": "SPF (Sender Policy Framework)",
        "option_c": "WPA3",
        "option_d": "AES-256",
        "correct_answer": "B",
        "explanation": "SPF (Sender Policy Framework) is an email authentication method that defines which mail servers are authorized to send email on behalf of your domain.",
        "category": "phishing",
    },
    {
        "question_text": "What does 'DKIM' (DomainKeys Identified Mail) add to emails to prevent tampering?",
        "option_a": "A dynamic verification phone number.",
        "option_b": "A digital signature that verifies the email was sent by the domain owner.",
        "option_c": "An automatic antivirus scanning certificate.",
        "option_d": "A secondary firewall wrapper.",
        "correct_answer": "B",
        "explanation": "DKIM provides a cryptographic signature on emails. Receiving servers verify this signature against public keys published in the sender's DNS, ensuring the message was not altered in transit.",
        "category": "phishing",
    },
    {
        "question_text": "What is the primary role of a 'DMARC' policy?",
        "option_a": "Automatically encrypting outgoing email attachments.",
        "option_b": "Instructing receiving servers on how to handle emails that fail SPF or DKIM checks.",
        "option_c": "Filtering out spam emails containing commercial keywords.",
        "option_d": "Enforcing two-factor authentication on local mail apps.",
        "correct_answer": "B",
        "explanation": "DMARC (Domain-based Message Authentication, Reporting, and Conformance) coordinates SPF and DKIM checks, telling receiving servers to reject, quarantine, or monitor failed emails.",
        "category": "phishing",
    },
    {
        "question_text": "Which of the following is a giveaway that a corporate login portal has been cloned by a phisher?",
        "option_a": "The login page asks for your username and password.",
        "option_b": "The browser shows a warning or the URL bar displays a domain unrelated to your company.",
        "option_c": "The page load time is slightly faster than usual.",
        "option_d": "The background image is high-resolution.",
        "correct_answer": "B",
        "explanation": "Cloned portals look identical to real ones. The only true indicator is the URL. Always check the domain name in the address bar before typing sensitive passwords.",
        "category": "phishing",
    },
    {
        "question_text": "A popup on your phone says: 'Your device is infected! Click here to download cleaner.' This is a form of:",
        "option_a": "Ransomware payload",
        "option_b": "Scareware/Malvertising",
        "option_c": "Pharming script",
        "option_d": "Buffer overflow",
        "correct_answer": "B",
        "explanation": "Scareware uses fear to trick users into downloading malicious software, often masqueraded as 'security updates' or 'virus cleaners'.",
        "category": "phishing",
    },
    {
        "question_text": "Why is business email compromise (BEC) so successful?",
        "option_a": "It bypasses standard antivirus scanners because it contains no malware files or link attachments.",
        "option_b": "It completely shuts down the mail servers during the attack.",
        "option_c": "It automatically intercepts banking networks using rootkits.",
        "option_d": "It exploits default admin passwords on local routers.",
        "correct_answer": "A",
        "explanation": "BEC relies entirely on social engineering and conversation. Because they are plain-text requests sent from spoofed or hijacked accounts, they do not trigger signature-based filters.",
        "category": "phishing",
    },
    {
        "question_text": "An email greets you with 'Dear customer' instead of your name. This is a common sign of:",
        "option_a": "Spear phishing",
        "option_b": "Mass/generic phishing",
        "option_c": "Whaling",
        "option_d": "Credential harvesting",
        "correct_answer": "B",
        "explanation": "Generic greetings indicate a mass email campaign. Legitimate banks and retailers usually address you by your full name.",
        "category": "phishing",
    },
    {
        "question_text": "What is 'baiting' in the context of cyber safety?",
        "option_a": "Intercepting traffic from public routers.",
        "option_b": "Offering free gifts, movie downloads, or USBs to lure victims into downloading malware.",
        "option_c": "Brute-forcing admin accounts using a dictionary file.",
        "option_d": "Deleting log files after a database breach.",
        "correct_answer": "B",
        "explanation": "Baiting uses physical media or digital downloads that appeal to human curiosity or desire for free stuff to trick victims.",
        "category": "phishing",
    },
    {
        "question_text": "What does 'quid pro quo' mean in social engineering?",
        "option_a": "Stealing authorization tokens from a cookie directory.",
        "option_b": "Offering a service or benefit in exchange for sensitive information (e.g. tech support help).",
        "option_c": "Sending phishing emails in multiple languages.",
        "option_d": "Encrypting backup directories sequentially.",
        "correct_answer": "B",
        "explanation": "Quid pro quo ('something for something') involves an attacker promising a service, like free IT technical support, in exchange for login credentials or configuration details.",
        "category": "phishing",
    },
    {
        "question_text": "What is the primary objective of a 'credential harvester' page?",
        "option_a": "Decrypting system certificates locally.",
        "option_b": "To collect logins, passwords, and security answers via a fake portal.",
        "option_c": "Sending multiple spam emails to block communication ports.",
        "option_d": "Deleting user databases.",
        "correct_answer": "B",
        "explanation": "Credential harvesters are fake login sites created by phishers to steal usernames, passwords, and MFA credentials when users submit them.",
        "category": "phishing",
    },
    {
        "question_text": "What does a padlock icon in your browser's address bar signify?",
        "option_a": "The website is completely safe and free from fraud.",
        "option_b": "The connection between your browser and the website is encrypted.",
        "option_c": "The website has been verified by the federal government.",
        "option_d": "The website is private and cannot be visited by others.",
        "correct_answer": "B",
        "explanation": "The padlock icon confirms HTTPS encryption, meaning traffic cannot be sniffed in transit. It does NOT guarantee the website itself is not a phishing site.",
        "category": "phishing",
    },
    {
        "question_text": "Which tactic involves spoofing executive communications to authorize bulk gift card purchases?",
        "option_a": "Rootkit infection",
        "option_b": "Business Email Compromise (BEC)",
        "option_c": "DNS spoofing",
        "option_d": "Ransomware payout",
        "correct_answer": "B",
        "explanation": "Gift card scams are a frequent outcome of Business Email Compromise, where scammers convince staff members that the CEO needs urgent gift cards for client rewards.",
        "category": "phishing",
    },
    {
        "question_text": "How can you protect your organization from social engineering attacks?",
        "option_a": "By using stronger physical locking systems on server cages.",
        "option_b": "Through ongoing security awareness training and phishing simulations.",
        "option_c": "By disabling the local local area network connectivity.",
        "option_d": "Only by using outdated software that hackers do not study.",
        "correct_answer": "B",
        "explanation": "Because social engineering targets humans rather than technical vulnerabilities, education, validation habits, and testing are the most effective shields.",
        "category": "phishing",
    },
    {
        "question_text": "What does the term 'social engineering' mean in computer security?",
        "option_a": "Writing code to automatically map network topologies.",
        "option_b": "Manipulating people into performing actions or giving up confidential credentials.",
        "option_c": "Creating social media accounts for marketing purposes.",
        "option_d": "Upgrading server firmware across a company.",
        "correct_answer": "B",
        "explanation": "Social engineering describes the psychological manipulation of people into revealing secure access or personal data.",
        "category": "phishing",
    },
    {
        "question_text": "An email asks you to click a link to update details because your account had a suspicious login. You should first:",
        "option_a": "Click the link and submit your old password.",
        "option_b": "Verify the email headers or contact the sender through a known, trusted phone number.",
        "option_c": "Ignore it and wait for your account to get suspended.",
        "option_d": "Send your password to the sender directly to fix the issue.",
        "correct_answer": "B",
        "explanation": "Always confirm security notifications through independent channels, not via links or phone numbers provided in the email itself.",
        "category": "phishing",
    },
    {
        "question_text": "What is email headers inspection useful for?",
        "option_a": "Measuring the transmission speed of network routers.",
        "option_b": "Identifying the true sending source, IP address, and route of an email.",
        "option_c": "Deleting emails from remote mail servers.",
        "option_d": "Generating strong passwords.",
        "correct_answer": "B",
        "explanation": "Email headers trace the path of the email from origin to recipient. Inspecting them reveals the real sender address, which often differs from the display name.",
        "category": "phishing",
    },
    {
        "question_text": "What type of attack involves redirecting users to a fake website when they type a valid web address, often by poisoning local routers?",
        "option_a": "Spear phishing",
        "option_b": "Pharming",
        "option_c": "DDoS",
        "option_d": "Worm propagation",
        "correct_answer": "B",
        "explanation": "Pharming exploits DNS resolution. By corrupting DNS caches or local host files, it takes users to a fraudulent site even if they typed the correct URL.",
        "category": "phishing",
    },
    {
        "question_text": "Which of the following is a safe email attachment habit?",
        "option_a": "Open all attachments ending in .pdf or .doc without checking.",
        "option_b": "Only open unexpected attachments after calling the sender via a trusted method to confirm they sent it.",
        "option_c": "Double-click all attachments inside your spam folder.",
        "option_d": "Disable your security scanner to open files faster.",
        "correct_answer": "B",
        "explanation": "Email attachments are a major delivery mechanism for malware. Always confirm unexpected attachments directly before opening them.",
        "category": "phishing",
    },
    {
        "question_text": "Why should you never enter credentials on a website with a certificate error?",
        "option_a": "It means the website has too many concurrent users.",
        "option_b": "It suggests the connection is not secure or your traffic is being intercepted by an attacker.",
        "option_c": "The browser is out of memory.",
        "option_d": "The site will charge you a fee.",
        "correct_answer": "B",
        "explanation": "Certificate errors indicate that the SSL/TLS identity of the site cannot be validated. This occurs during Man-in-the-Middle attacks or when using fraudulent server configurations.",
        "category": "phishing",
    },

    # ===== MALWARE (35 templates) =====
    {
        "question_text": "How does a computer virus differ from a computer worm?",
        "option_a": "A virus is malicious software; a worm is harmless code.",
        "option_b": "A virus requires human execution to propagate, while a worm can self-replicate and spread over networks automatically.",
        "option_c": "A virus targets hardware, while a worm targets cloud databases.",
        "option_d": "A virus propagates through USB drives only.",
        "correct_answer": "B",
        "explanation": "Viruses need a host program and human action (e.g. running a file) to spread. Worms are standalone programs that exploit vulnerabilities to travel between systems automatically.",
        "category": "malware",
    },
    {
        "question_text": "Which of the following is designed to capture all keyboard inputs from a user?",
        "option_a": "Adware",
        "option_b": "Keylogger",
        "option_c": "Ransomware",
        "option_d": "Trojan Horse",
        "correct_answer": "B",
        "explanation": "Keyloggers record keyboard strokes to harvest usernames, passwords, credit card numbers, and other typed credentials.",
        "category": "malware",
    },
    {
        "question_text": "What is the primary action of 'ransomware'?",
        "option_a": "Displaying multiple unwanted pop-up advertisements.",
        "option_b": "Encrypting files on a system and demanding payment to restore access.",
        "option_c": "Stealing bandwidth to carry out network scanning.",
        "option_d": "Deleting temporary directories.",
        "correct_answer": "B",
        "explanation": "Ransomware locks or encrypts local user files, demanding a ransom payment (usually in cryptocurrency) in exchange for the decryption key.",
        "category": "malware",
    },
    {
        "question_text": "What is a 'Trojan Horse' in computer security?",
        "option_a": "A mechanical lock for server hardware racks.",
        "option_b": "Malicious software disguised as a legitimate program.",
        "option_c": "Software that monitors temperature of CPU processors.",
        "option_d": "A program that accelerates download speeds.",
        "correct_answer": "B",
        "explanation": "Trojans appear safe and useful (like games or utility apps), tricking users into downloading them, only to install spyware, backdoors, or rootkits behind the scenes.",
        "category": "malware",
    },
    {
        "question_text": "What is the primary function of 'spyware'?",
        "option_a": "Helping users find hidden files on their hard drive.",
        "option_b": "Covertly gathering user data and internet activity without consent.",
        "option_c": "Improving operating system boot times.",
        "option_d": "Filtering spam emails from inbox lists.",
        "correct_answer": "B",
        "explanation": "Spyware operates silently in the background, logging actions, browser history, passwords, and sensitive information to send to the attacker.",
        "category": "malware",
    },
    {
        "question_text": "What does 'adware' do?",
        "option_a": "Encrypts your browser database folders.",
        "option_b": "Automatically generates and displays intrusive advertisements on a computer.",
        "option_c": "Deactivates local network firewalls.",
        "option_d": "Increases computer storage space.",
        "correct_answer": "B",
        "explanation": "Adware automatically renders advertising material (pop-ups, banners) to generate revenue for its author, often slowing down the device and tracking user habits.",
        "category": "malware",
    },
    {
        "question_text": "Which type of malware integrates deep into the operating system kernel to hide files, processes, and network connections from detection?",
        "option_a": "Trojan horse",
        "option_b": "Rootkit",
        "option_c": "Spyware",
        "option_d": "Worm",
        "correct_answer": "B",
        "explanation": "Rootkits gain administrator/kernel access to hide their presence and that of other malware from standard system tools and antivirus scanners.",
        "category": "malware",
    },
    {
        "question_text": "What defines a 'logic bomb'?",
        "option_a": "A mechanical explosive triggered by software.",
        "option_b": "Malicious code that triggers its payload only when specific conditions or dates are met.",
        "option_c": "Malware that deletes files based on user search queries.",
        "option_d": "A browser extension that blocks phishing URLs.",
        "correct_answer": "B",
        "explanation": "Logic bombs lie dormant until triggered by an event, such as a specific date, a user action, or an employee being removed from the employee database.",
        "category": "malware",
    },
    {
        "question_text": "What is a 'backdoor'?",
        "option_a": "A physical exit route from a data center.",
        "option_b": "A mechanism that bypasses normal security authentication to allow remote access to a system.",
        "option_c": "An old version of standard database schemas.",
        "option_d": "An encryption key generated during setup.",
        "correct_answer": "B",
        "explanation": "Backdoors provide unauthorized remote access to a compromised system, enabling attackers to execute commands, transfer files, or steal data at will.",
        "category": "malware",
    },
    {
        "question_text": "What does a 'drive-by download' mean?",
        "option_a": "Downloading software while driving a car via cellular hotspots.",
        "option_b": "Unintended download of malware when visiting an infected website, requiring no user clicking or action.",
        "option_c": "Using peer-to-peer networks to distribute large video files.",
        "option_d": "Updating applications while system logs are clearing.",
        "correct_answer": "B",
        "explanation": "Drive-by downloads exploit browser or plug-in vulnerabilities. Simply visiting a compromised webpage downloads and runs malicious code without your consent.",
        "category": "malware",
    },
    {
        "question_text": "Which of the following is a network of compromised computers controlled remotely by a command-and-control server?",
        "option_a": "Local Area Network (LAN)",
        "option_b": "Botnet",
        "option_c": "Intranet",
        "option_d": "Virtual Private Network (VPN)",
        "correct_answer": "B",
        "explanation": "Botnets (robot networks) consist of 'zombie' computers infected with malware that allows attackers to control them simultaneously for DDoS attacks or spam campaigns.",
        "category": "malware",
    },
    {
        "question_text": "What is a 'keylogger'?",
        "option_a": "A tool to generate strong security keys.",
        "option_b": "Spyware that records keystrokes to steal sensitive information.",
        "option_c": "A database system to manage credentials.",
        "option_d": "A hardware lock for office doors.",
        "correct_answer": "B",
        "explanation": "Keyloggers capture keyboard activity. They are used to steal personal messages, banking data, passwords, and private correspondence.",
        "category": "malware",
    },
    {
        "question_text": "What type of malware exploits vulnerabilities in macros within documents like Microsoft Word or Excel?",
        "option_a": "Trojan horse",
        "option_b": "Macro virus",
        "option_c": "Spyware payload",
        "option_d": "Logic bomb",
        "correct_answer": "B",
        "explanation": "Macro viruses are written in macro languages used by applications like Microsoft Office. They spread when macro execution is enabled inside documents.",
        "category": "malware",
    },
    {
        "question_text": "What is 'ransomware-as-a-service' (RaaS)?",
        "option_a": "Free ransomware protection services provided by security firms.",
        "option_b": "A business model where developers rent out ransomware code to affiliates who carry out attacks.",
        "option_c": "A cloud backup recovery service.",
        "option_d": "A training platform for secure software coding.",
        "correct_answer": "B",
        "explanation": "RaaS is a model where ransomware creators sell or lease their encryption code to other hackers (affiliates) in exchange for a cut of the paid ransom.",
        "category": "malware",
    },
    {
        "question_text": "Which is the best first step to take if you realize ransomware has started encrypting your network drive?",
        "option_a": "Shut down or disconnect the affected computer from the network immediately.",
        "option_b": "Wait for the encryption to finish and pay the hackers.",
        "option_c": "Delete all antivirus software to free up processor speeds.",
        "option_d": "Share the encryption warning screen on social media channels.",
        "correct_answer": "A",
        "explanation": "Disconnecting the computer from the network stops the ransomware from reaching and encrypting shared drives and other computers on the LAN.",
        "category": "malware",
    },
    {
        "question_text": "What makes 'fileless malware' difficult for traditional antivirus software to detect?",
        "option_a": "It only infects computers with disabled power grids.",
        "option_b": "It resides purely in system RAM and uses legitimate administrative tools (like PowerShell) rather than creating files on disk.",
        "option_c": "It is written in binary code that firewalls do not scan.",
        "option_d": "It requires physical entry into data center rooms.",
        "correct_answer": "B",
        "explanation": "Fileless malware doesn't write executable files to the hard drive, making traditional file-signature scanners ineffective. It runs directly in memory using built-in system tools.",
        "category": "malware",
    },
    {
        "question_text": "What is a 'malicious macro'?",
        "option_a": "A shortcut code that accelerates internet speed.",
        "option_b": "Embedded instructions inside document files that download and install malware when opened.",
        "option_c": "A hardware component used to lock screens.",
        "option_d": "A server partition that isolates viruses.",
        "correct_answer": "B",
        "explanation": "Attackers write macros inside spreadsheets or document templates that automatically connect to a remote server to download malware when the user enables macros.",
        "category": "malware",
    },
    {
        "question_text": "Which of the following is a recommended protection against malware?",
        "option_a": "Keeping your operating system and applications updated with security patches.",
        "option_b": "Disabling Windows Defender to save CPU memory.",
        "option_c": "Sharing all login credentials with IT technicians.",
        "option_d": "Rebooting the system hourly.",
        "correct_answer": "A",
        "explanation": "Most malware campaigns exploit known software bugs. Patching closes these entry points, preventing exploit kits from executing malware.",
        "category": "malware",
    },
    {
        "question_text": "What does a 'zero-day exploit' mean?",
        "option_a": "An exploit targeting a vulnerability that the software developer has known about for months.",
        "option_b": "An attack targeting a newly discovered vulnerability for which no security patch is available.",
        "option_c": "A software bug that automatically expires after one day.",
        "option_d": "A trial version of security software.",
        "correct_answer": "B",
        "explanation": "Zero-day exploits exploit security flaws unknown to the vendor, leaving users undefended ('zero days' of notice) until a patch is released.",
        "category": "malware",
    },
    {
        "question_text": "What does the term 'malware signature' refer to?",
        "option_a": "The digital signature of a security administrator.",
        "option_b": "A unique sequence of bytes or hash value that identifies a specific malware sample.",
        "option_c": "The handwriting of a hacker.",
        "option_d": "The system config folder where malware logs are saved.",
        "correct_answer": "B",
        "explanation": "Antivirus engines compare files against a list of known malware signatures (fingerprints) to detect threat occurrences instantly.",
        "category": "malware",
    },
    {
        "question_text": "Why are default credentials on IoT (Internet of Things) devices dangerous?",
        "option_a": "They use too much data bandwidth.",
        "option_b": "They are easily guessed, allowing botnets to hijack them in bulk.",
        "option_c": "They prevent software updates.",
        "option_d": "They disrupt home electrical circuits.",
        "correct_answer": "B",
        "explanation": "Mirai and similar botnets scan the internet for IoT devices using default logins (e.g. admin/admin) to build massive networks of zombie devices.",
        "category": "malware",
    },
    {
        "question_text": "What is 'scareware'?",
        "option_a": "Malicious code that deletes all document folders.",
        "option_b": "Malware that triggers false security alerts to scare users into purchasing useless software.",
        "option_c": "A utility to check motherboard integrity.",
        "option_d": "Games that contain graphic horror themes.",
        "correct_answer": "B",
        "explanation": "Scareware uses realistic-looking fake system notifications ('Warning: 137 Viruses Found!') to trick users into downloading malicious executables or paying for fake utilities.",
        "category": "malware",
    },
    {
        "question_text": "What type of malware targets Android or iOS mobile devices specifically?",
        "option_a": "Mobile malware (e.g. spyware, cloned APKs, malicious apps)",
        "option_b": "BIOS malware",
        "option_c": "Router botnet scripts",
        "option_d": "Kernel rootkits",
        "correct_answer": "A",
        "explanation": "Mobile malware is designed for phone operating systems, typically distributed via unofficial stores as fake utilities or game modifications.",
        "category": "malware",
    },
    {
        "question_text": "What does an antivirus quarantine folder do?",
        "option_a": "It deletes the suspected threat permanently.",
        "option_b": "It isolates malicious files in a secure, encrypted folder to prevent them from running.",
        "option_c": "It sends the files back to the attacker.",
        "option_d": "It shares the files with everyone on your network.",
        "correct_answer": "B",
        "explanation": "Quarantine isolates the threat so it cannot harm the system while allowing you to inspect it or restore it if it was a false positive.",
        "category": "malware",
    },
    {
        "question_text": "Which of the following is safe advice regarding mobile app installations?",
        "option_a": "Only install apps from official stores (like Google Play or Apple App Store) and check permissions.",
        "option_b": "Download APKs from third-party forums to avoid app store fees.",
        "option_c": "Enable 'Install from Unknown Sources' indefinitely.",
        "option_d": "Grant administrator permission to all downloaded utility apps.",
        "correct_answer": "A",
        "explanation": "Official stores scan submissions for malware. Sideloading apps from unknown websites bypasses these protections, presenting major security risks.",
        "category": "malware",
    },
    {
        "question_text": "What is 'spyware' primarily interested in collecting?",
        "option_a": "The manufacturer of your computer motherboard.",
        "option_b": "Passwords, keystrokes, browsing histories, and financial account credentials.",
        "option_c": "The speed of your internet router.",
        "option_d": "Empty directories on your desktop.",
        "correct_answer": "B",
        "explanation": "Spyware targets high-value personal data that can be used for financial fraud, identity theft, or business espionage.",
        "category": "malware",
    },
    {
        "question_text": "Which action represents high cyber safety risk when using emails?",
        "option_a": "Using plain text format to write replies.",
        "option_b": "Opening attachments from unknown senders without scanning them.",
        "option_c": "Deleting emails from unknown senders.",
        "option_d": "Marking non-malicious marketing mail as spam.",
        "correct_answer": "B",
        "explanation": "Opening unsolicited attachments (like .js, .scr, or macro-enabled documents) launches code that downloads and runs malware directly on your system.",
        "category": "malware",
    },
    {
        "question_text": "What is 'ransomware encryption'?",
        "option_a": "A security process to back up database files.",
        "option_b": "The cryptographic process of locking local user data so only the hackers' key can restore them.",
        "option_c": "Using secure passphrases to set up email servers.",
        "option_d": "A utility to compress large server logs.",
        "correct_answer": "B",
        "explanation": "Cryptor-ransomware uses strong encryption algorithms (like RSA or AES) that are impossible to crack without the key, making security backups critical.",
        "category": "malware",
    },
    {
        "question_text": "Which of the following is true about payment to ransomware groups?",
        "option_a": "Payment guarantees you will recover all files safely.",
        "option_b": "Payment funds future crimes and does not guarantee a working decryption key is provided.",
        "option_c": "Government agencies reimburse paid ransoms.",
        "option_d": "Decryptor keys work automatically on all other systems.",
        "correct_answer": "B",
        "explanation": "Decryption keys are often buggy or not delivered. Paying funds criminal operations and marks you as a willing target for future attacks.",
        "category": "malware",
    },

    # ===== HACKING (12 templates) =====
    {
        "question_text": "What is the primary difference between a White Hat and a Black Hat hacker?",
        "option_a": "White hats use Windows; black hats use Linux.",
        "option_b": "White hats have permission and hack to improve security; black hats hack illegally for personal gain.",
        "option_c": "White hats work during the day; black hats hack at night.",
        "option_d": "White hats do not write code; black hats write malicious scripts.",
        "correct_answer": "B",
        "explanation": "White hats (ethical hackers) are authorized to find and report vulnerabilities. Black hats exploit security flaws illegally for financial or political gain.",
        "category": "hacking",
    },
    {
        "question_text": "What occurs during a Distributed Denial of Service (DDoS) attack?",
        "option_a": "An attacker physically breaks into server rooms.",
        "option_b": "A server is flooded with traffic from multiple sources to make it unavailable.",
        "option_c": "Database credentials are leaked on online forums.",
        "option_d": "Antivirus software is remotely deactivated.",
        "correct_answer": "B",
        "explanation": "DDoS attacks use botnets (networks of hijacked systems) to swamp a target server with traffic, overload its resources, and force it offline.",
        "category": "hacking",
    },
    {
        "question_text": "What is a 'zero-day' vulnerability?",
        "option_a": "A vulnerability that has been fully patched by the manufacturer.",
        "option_b": "A software security flaw that is unknown to the vendor, with no patch available.",
        "option_c": "A password check bypass that expires in 24 hours.",
        "option_d": "A bug that only affects new computers.",
        "correct_answer": "B",
        "explanation": "Zero-day vulnerabilities represent holes in software before creators are aware of them. Hackers exploit these gaps before a defense can be designed.",
        "category": "hacking",
    },
    {
        "question_text": "What does 'SQL Injection' (SQLi) target?",
        "option_a": "Local network routers and access points.",
        "option_b": "Database engines by submitting malicious input queries via input forms.",
        "option_c": "Wireless keyboard signals.",
        "option_d": "Power supplies inside data servers.",
        "correct_answer": "B",
        "explanation": "SQL Injection inserts malicious SQL statements into input boxes, tricking database backends into releasing secret information or executing unauthorized commands.",
        "category": "hacking",
    },
    {
        "question_text": "What is a 'man-in-the-middle' (MitM) attack?",
        "option_a": "A physical theft of database drives.",
        "option_b": "An attacker intercepts and alters communications between two parties without their knowledge.",
        "option_c": "Hacking into multiple routers at the same time.",
        "option_d": "An employee sharing credentials with a contractor.",
        "correct_answer": "B",
        "explanation": "MitM attacks happen when data is intercepted on unencrypted networks (e.g. public Wi-Fi). Attackers spy on logins, messages, and session tokens.",
        "category": "hacking",
    },
    {
        "question_text": "What is 'ethical hacking'?",
        "option_a": "Writing open-source software.",
        "option_b": "Authorized hacking to find vulnerabilities and strengthen defenses.",
        "option_c": "Hacktivism targeting controversial corporations.",
        "option_d": "Using default configurations to set up servers.",
        "correct_answer": "B",
        "explanation": "Ethical hacking uses the same techniques as cybercriminals but with formal permission, aiming to correct security gaps before they are exploited.",
        "category": "hacking",
    },
    {
        "question_text": "Which attack involves guessing user passwords by testing millions of common combinations automatically?",
        "option_a": "SQL injection",
        "option_b": "Brute-force / Dictionary attack",
        "option_c": "Phishing campaign",
        "option_d": "MitM interception",
        "correct_answer": "B",
        "explanation": "Brute-force attacks use software to try millions of common password combinations (dictionary words, dates, character sets) until the correct login is guessed.",
        "category": "hacking",
    },
    {
        "question_text": "What is a 'honeypot' in network security?",
        "option_a": "A backup directory for executive documents.",
        "option_b": "A decoy system set up to lure and monitor hackers.",
        "option_c": "A database containing all user passwords.",
        "option_d": "A virus that infects smart printers.",
        "correct_answer": "B",
        "explanation": "Honeypots are decoy databases or networks set up to detect unauthorized access early, divert hackers from live assets, and study their attack tactics.",
        "category": "hacking",
    },
    {
        "question_text": "What does a 'firewall' primarily do?",
        "option_a": "Monitors CPU temperature to prevent fire hazards.",
        "option_b": "Monitors and filters incoming and outgoing network traffic based on rules.",
        "option_c": "Automatically generates secure master passwords.",
        "option_d": "Scans physical drives for infected documents.",
        "correct_answer": "B",
        "explanation": "Firewalls establish a barrier between trusted internal networks and untrusted external networks (like the internet), blocking unauthorized connection attempts.",
        "category": "hacking",
    },
    {
        "question_text": "What is the primary indicator of a SQL Injection vulnerability in a login page?",
        "option_a": "The page takes too long to load.",
        "option_b": "Entering quotes or database code triggers system query errors or lets you bypass the password box.",
        "option_c": "The logo is displayed in grayscale.",
        "option_d": "The domain is changed to a .net URL.",
        "correct_answer": "B",
        "explanation": "Improperly formatted database queries allow input containing quotes to break commands, bypassing authentication checks entirely.",
        "category": "hacking",
    },
    {
        "question_text": "What is 'DNS Spoofing' (or cache poisoning)?",
        "option_a": "Altering hardware configurations on wireless routers.",
        "option_b": "Manipulating domain resolution to direct traffic to fake websites.",
        "option_c": "Sending multiple copy spam emails to users.",
        "option_d": "Bypassing login security using root privileges.",
        "correct_answer": "B",
        "explanation": "DNS Spoofing updates database servers with false DNS records, directing browsers to a fraudulent site even if the correct address is requested.",
        "category": "hacking",
    },
    {
        "question_text": "Which protocol encrypts your internet traffic to ensure third parties on a network cannot inspect it?",
        "option_a": "HTTP",
        "option_b": "HTTPS / SSL / TLS",
        "option_c": "Telnet",
        "option_d": "FTP",
        "correct_answer": "B",
        "explanation": "HTTPS encrypts the session channel, protecting data from Man-in-the-Middle snooping on local Wi-Fi hotspots.",
        "category": "hacking",
    },

    # ===== SPOOFING (12 templates) =====
    {
        "question_text": "What is the core concept of 'spoofing'?",
        "option_a": "Shutting down target servers using malicious scripts.",
        "option_b": "Disguising a communication sender to appear as a trusted contact.",
        "option_c": "Deleting system log files after a database breach.",
        "option_d": "Encrypting local documents using RSA algorithms.",
        "correct_answer": "B",
        "explanation": "Spoofing involves masquerading email senders, caller IDs, or IP addresses to trick victims into believing the sender is authentic.",
        "category": "spoofing",
    },
    {
        "question_text": "What is 'IP Spoofing'?",
        "option_a": "Changing the physical hardware MAC address on routers.",
        "option_b": "Modifying packet headers to show a fake source IP address.",
        "option_c": "Stealing wireless bandwidth from neighbor homes.",
        "option_d": "Deleting the DNS cache from your operating system.",
        "correct_answer": "B",
        "explanation": "IP Spoofing changes the source IP in packet headers to mimic a trusted system, allowing hackers to bypass firewall rules that trust specific IP ranges.",
        "category": "spoofing",
    },
    {
        "question_text": "What happens during a Caller ID spoofing attack?",
        "option_a": "The attacker intercepts all incoming voice calls.",
        "option_b": "The attacker displays a fake phone number on the victim's screen.",
        "option_c": "The phone's operating system gets encrypted.",
        "option_d": "The SIM card is cloned remotely.",
        "correct_answer": "B",
        "explanation": "Caller ID spoofing changes the caller name or number shown on Caller ID, often mimicking banks or government agencies to trick targets.",
        "category": "spoofing",
    },
    {
        "question_text": "What is email address spoofing?",
        "option_a": "Setting up multiple fake email accounts.",
        "option_b": "Forging email headers so the message appears from a trusted domain.",
        "option_c": "Flooding an inbox with useless promotions.",
        "option_d": "Cracking password keys using brute-force.",
        "correct_answer": "B",
        "explanation": "Email spoofing displays a false sender address. SPF, DKIM, and DMARC are DNS policies specifically designed to identify and block spoofed emails.",
        "category": "spoofing",
    },
    {
        "question_text": "How can you detect Caller ID spoofing?",
        "option_a": "By listening to the line static.",
        "option_b": "By hanging up and calling the organization back using an official number from their website.",
        "option_c": "Caller ID spoofing is impossible to detect.",
        "option_d": "By checking the signal strength of your device.",
        "correct_answer": "B",
        "explanation": "Because incoming numbers can be easily forged, never give out details on unsolicited calls. Call the caller back using the official customer service line.",
        "category": "spoofing",
    },
    {
        "question_text": "What does 'MAC Spoofing' involve?",
        "option_a": "Hacking Apple computers specifically.",
        "option_b": "Changing the factory-assigned media access control (MAC) address of a network adapter.",
        "option_c": "Altering the database schema of web hosts.",
        "option_d": "Decrypting system certificates.",
        "correct_answer": "B",
        "explanation": "MAC Spoofing changes the hardware address of a network card to match an authorized device, bypass security systems, or hide identity on local networks.",
        "category": "spoofing",
    },
    {
        "question_text": "What is the primary indicator of website domain spoofing?",
        "option_a": "The website uses custom fonts.",
        "option_b": "The domain name is slightly altered (e.g. paypa1.com or microsoff.com).",
        "option_c": "The page displays a copyright notice.",
        "option_d": "The website shows an secure padlock.",
        "correct_answer": "B",
        "explanation": "Domain spoofing uses typosquatting or look-alike characters (homoglyphs) to trick users into believing they are on a legitimate website.",
        "category": "spoofing",
    },
    {
        "question_text": "Which protocol prevents ARP spoofing on a local area network?",
        "option_a": "HTTP",
        "option_b": "Dynamic ARP Inspection (DAI)",
        "option_c": "Telnet",
        "option_d": "SMTP",
        "correct_answer": "B",
        "explanation": "Dynamic ARP Inspection (DAI) verifies ARP packets on a local switch, blocking invalid ARP bindings that attackers use to spoof local routers.",
        "category": "spoofing",
    },
    {
        "question_text": "What is 'GPS Spoofing'?",
        "option_a": "Manipulating search engines to show fake locations.",
        "option_b": "Broadcasting fake GPS signals to trick GPS receivers into displaying incorrect location data.",
        "option_c": "Using a proxy server to mask IP addresses.",
        "option_d": "Editing screen lock maps.",
        "correct_answer": "B",
        "explanation": "GPS spoofing broadcasts fake location signals, overriding real satellite data to disrupt navigation systems on drones, ships, or mapping apps.",
        "category": "spoofing",
    },
    {
        "question_text": "What does a phisher achieve by spoofing trusted corporate display names in email campaigns?",
        "option_a": "They gain administrative server access.",
        "option_b": "They bypass basic spam filters that only check the display name, misleading the user.",
        "option_c": "They disable local system update programs.",
        "option_d": "They delete backup databases.",
        "correct_answer": "B",
        "explanation": "Most mobile email clients only show the display name rather than the full email address. Spoofing this name tricks users into opening fraudulent messages.",
        "category": "spoofing",
    },
    {
        "question_text": "What is the risk of an 'Evil Twin' spoofing attack?",
        "option_a": "Someone physically clones your identity card.",
        "option_b": "An attacker creates a clone of a legitimate Wi-Fi network to capture users' traffic.",
        "option_c": "Your computer motherboard is damaged.",
        "option_d": "Your software updates are blocked.",
        "correct_answer": "B",
        "explanation": "Evil Twins are fake Wi-Fi spots named identically to trusted venue hotspots, tricking devices into connecting automatically so the attacker can spy on traffic.",
        "category": "spoofing",
    },
    {
        "question_text": "How can you protect your company domain from being spoofed by unauthorized email senders?",
        "option_a": "By using a stronger master database password.",
        "option_b": "By configuring SPF, DKIM, and DMARC records in your DNS setup.",
        "option_c": "By disabling outbound email communication entirely.",
        "option_d": "By updating local operating system security patches.",
        "correct_answer": "B",
        "explanation": "Configuring SPF, DKIM, and DMARC specifies authentication parameters, helping email providers reject fake emails claiming to come from your domain.",
        "category": "spoofing",
    },

    # ===== CYBER BULLYING (10 templates) =====
    {
        "question_text": "What constitutes 'cyberbullying'?",
        "option_a": "Sending high volumes of marketing emails to potential buyers.",
        "option_b": "Using digital devices to repeatedly send hostile, intimidating, or harassing messages to target someone.",
        "option_c": "Accessing computer systems without authorization.",
        "option_d": "Using ad-blocking extensions on browsers.",
        "correct_answer": "B",
        "explanation": "Cyberbullying is intentional, persistent harassment carried out online (social media, chat apps, forums) to intimidate or humiliate the victim.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "What is 'doxxing'?",
        "option_a": "Recovering lost documents using system commands.",
        "option_b": "Publishing private personal information about someone online without consent to invite harassment.",
        "option_c": "Converting document files into portable format.",
        "option_d": "Backing up local server database folders.",
        "correct_answer": "B",
        "explanation": "Doxxing (document tracing) involves searching for and publishing private addresses, phone numbers, or employers of an individual to expose them to abuse.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "What does 'cyberstalking' mean?",
        "option_a": "Using online resources to monitor and follow target accounts to steal passwords.",
        "option_b": "Using internet communications to repeatedly stalk, harass, or threaten a person, causing fear.",
        "option_c": "Searching for security issues inside cloud networks.",
        "option_d": "Tracking software update release dates.",
        "correct_answer": "B",
        "explanation": "Cyberstalking is the use of email, social media, or other digital communications to spy on, stalk, and repeatedly threaten someone, making them fear for their safety.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "If you witness online harassment on a social media platform, what is the best first step?",
        "option_a": "Join in the comments to argue with the cyberbully.",
        "option_b": "Report the abusive behavior and posts to the platform administration and block the bully.",
        "option_c": "Ignore it completely to avoid being targeted.",
        "option_d": "Share the victim's personal phone number to help them.",
        "correct_answer": "B",
        "explanation": "Platforms have reporting mechanisms to suspend accounts violating terms of service. Engaging with bullies often escalates the harassment.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "What is 'cyberharassment'?",
        "option_a": "A system update that takes too long.",
        "option_b": "Repeatedly sending offensive or threatening emails or messages to an individual.",
        "option_c": "Scanning database ports for vulnerabilities.",
        "option_d": "Publishing online ads that have loud audio.",
        "correct_answer": "B",
        "explanation": "Cyberharassment consists of non-physical harassment like offensive messages, insults, and threats delivered via email, text, or social media.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "What is the primary danger of doxxing?",
        "option_a": "It causes physical device failure.",
        "option_b": "It exposes the victim's offline address and details, potentially inviting physical threats or swatting.",
        "option_c": "It deletes the victim's cloud data files.",
        "option_d": "It slows the victim's home router.",
        "correct_answer": "B",
        "explanation": "Doxxing translates online harassment into offline risk by publicizing locations, exposing victims to physical harm, harassment at work, or vandalism.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "Which action is recommended if a child or student is being cyberbullied?",
        "option_a": "Keep screenshots of the cyberbullying as evidence, block the sender, and speak with parents or school authorities.",
        "option_b": "Reply with aggressive insults to show strength.",
        "option_c": "Delete all social media accounts and never tell anyone.",
        "option_d": "Share the bully's address publicly.",
        "correct_answer": "A",
        "explanation": "Screenshots provide documentation of harassment. Block senders immediately to stop direct contact, and report the issue to adults or platforms.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "What is 'flaming' in the context of cyberbullying?",
        "option_a": "Creating computer animations with fire.",
        "option_b": "Online fights using angry, offensive language in public chatrooms or comment sections.",
        "option_c": "Sending virus attachments to delete user logs.",
        "option_d": "Hacking database login controls.",
        "correct_answer": "B",
        "explanation": "Flaming describes heated, hostile exchanges online, where cyberbullies post insults, slurs, and aggressive messages to attack a victim publicly.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "What is 'trolling'?",
        "option_a": "Searching for security bugs inside system kernels.",
        "option_b": "Deliberately posting provocative, offensive, or off-topic messages online to derail discussions and upset users.",
        "option_c": "Developing software programs that block pop-up ads.",
        "option_d": "Sharing files across local directories.",
        "correct_answer": "B",
        "explanation": "Trolling is the act of posting baiting statements online to provoke emotional reactions, arguments, and distress in other users.",
        "category": "cyber_bullying",
    },
    {
        "question_text": "How can you protect your personal info from being doxxed online?",
        "option_a": "Avoid sharing address, phone number, and location details on public social media profiles.",
        "option_b": "Only use lowercase letters in your passwords.",
        "option_c": "Update your computer hardware weekly.",
        "option_d": "Accept friend requests from all random profiles.",
        "correct_answer": "A",
        "explanation": "Doxxers look for public details. Minimizing personal data on public profiles prevents attackers from linking online profiles to your offline life.",
        "category": "cyber_bullying",
    },

    # ===== DEFAMATION (10 templates) =====
    {
        "question_text": "What is 'cyber defamation'?",
        "option_a": "Shutting down target servers using malicious scripts.",
        "option_b": "Publishing false, damaging statements about someone on the internet that harms their reputation.",
        "option_c": "Developing malware that monitors keyboard inputs.",
        "option_d": "Creating mock software backups without encryption.",
        "correct_answer": "B",
        "explanation": "Defamation involves harming a person's reputation through false statements. When done online (blogs, social media, forums), it is cyber defamation.",
        "category": "defamation",
    },
    {
        "question_text": "What is the difference between written defamation (libel) and spoken defamation (slander) in the cyber space?",
        "option_a": "Libel is permanent (like social posts or articles); slander is temporary (like live video streams or audio chats).",
        "option_b": "Libel is legal; slander is criminal.",
        "option_c": "Libel targets corporations; slander targets individuals.",
        "option_d": "There is no legal difference in cyber space.",
        "correct_answer": "A",
        "explanation": "Libel applies to written or permanent statements (social media posts, tweets, blog posts). Slander refers to spoken or transitory statements (voice rooms, unrecorded live audio).",
        "category": "defamation",
    },
    {
        "question_text": "If you share or retweet a defamatory post written by someone else, what is the legal risk?",
        "option_a": "No risk — only the original author is liable.",
        "option_b": "You can be held legally liable for republishing defamatory statements.",
        "option_c": "You will only be fined if the post gets 1,000 views.",
        "option_d": "Republishing is protected by all social media agreements.",
        "correct_answer": "B",
        "explanation": "Under many cyber laws, sharing, retweeting, or republishing defamatory content can make you legally liable alongside the original author.",
        "category": "defamation",
    },
    {
        "question_text": "Which of the following is a defense against a cyber defamation accusation?",
        "option_a": "The statement was posted anonymously.",
        "option_b": "The statement was entirely true.",
        "option_c": "The post was deleted within 10 minutes.",
        "option_d": "The statement was written in another language.",
        "correct_answer": "B",
        "explanation": "Truth is an absolute defense against defamation. If the published statement is factual and can be proven true, it is not legally defamatory.",
        "category": "defamation",
    },
    {
        "question_text": "An employee posts on LinkedIn that their former employer commits tax evasion, knowing it is false. This is:",
        "option_a": "Protected free speech.",
        "option_b": "Cyber defamation (specifically libel) and is legally actionable.",
        "option_c": "A breach of software configuration controls.",
        "option_d": "A logic bomb.",
        "correct_answer": "B",
        "explanation": "Publishing false assertions of crime about a business or person to damage their standing is a classic example of actionable defamation.",
        "category": "defamation",
    },
    {
        "question_text": "Under Section 499/500 of the Indian Penal Code (IPC), cyber defamation is considered:",
        "option_a": "A civil wrong only.",
        "option_b": "Both a civil wrong and a criminal offense punishable by imprisonment.",
        "option_c": "A copyright violation.",
        "option_d": "A minor server administration issue.",
        "correct_answer": "B",
        "explanation": "In India, defamation is both a civil tort and a criminal offense. Cyber defamation is handled under these IPC sections in conjunction with the IT Act, 2000.",
        "category": "defamation",
    },
    {
        "question_text": "What does the term 'opinion defense' mean in defamation cases?",
        "option_a": "Any statement can be legally protected if you start it with 'I think'.",
        "option_b": "Pure opinion statements that do not assert objective facts are generally protected from defamation claims.",
        "option_c": "Opinions can only be published in anonymous forums.",
        "option_d": "Businesses cannot have opinions.",
        "correct_answer": "B",
        "explanation": "To be defamatory, a statement must assert a false fact. Statements that are clearly subjective opinions (e.g. 'I didn't like their service') are generally protected.",
        "category": "defamation",
    },
    {
        "question_text": "Why is removing a defamatory post after being notified important?",
        "option_a": "It deletes the evidence from search engine server logs.",
        "option_b": "It mitigates damages and can prevent escalation of legal claims.",
        "option_c": "It automatically cancels all legal liability.",
        "option_d": "It updates browser databases.",
        "correct_answer": "B",
        "explanation": "Deleting the content limits the spread of the statement, which helps minimize reputational damage and demonstrates good faith in legal proceedings.",
        "category": "defamation",
    },
    {
        "question_text": "Can a company sue a consumer for cyber defamation over a false negative review online?",
        "option_a": "No, customer reviews are immune from cyber laws.",
        "option_b": "Yes, if the review makes false factual claims that harm the business's revenue.",
        "option_c": "Only if the review has over 10,000 views.",
        "option_d": "Only if the review was posted from outside the country.",
        "correct_answer": "B",
        "explanation": "Negative opinions are protected, but making false factual claims (e.g. 'This restaurant has rats in the kitchen' when it doesn't) to harm business is defamatory.",
        "category": "defamation",
    },
    {
        "question_text": "Which authority should you report severe cyber defamation to in India?",
        "option_a": "Your local internet service provider (ISP).",
        "option_b": "The Cyber Crime Portal (cybercrime.gov.in) or local Cyber Police station.",
        "option_c": "The Telecom Regulatory Authority.",
        "option_d": "Directly to the social media company's database team.",
        "correct_answer": "B",
        "explanation": "Official complaints of cyber crime, including severe cyber defamation, doxxing, and harassment, are reported via the National Cyber Crime Portal.",
        "category": "defamation",
    },

    # ===== SECURITY & LOGISTIC BACKBONE (16 templates) =====
    {
        "question_text": "What is the recommended minimum length for a secure master password?",
        "option_a": "6 characters",
        "option_b": "8 characters",
        "option_c": "12–16 characters, including numbers, uppercase, lowercase, and special characters",
        "option_d": "24 characters of pure numbers",
        "correct_answer": "C",
        "explanation": "Security standards recommend a password length of at least 12 characters, mixing types to prevent dictionary attacks.",
        "category": "password_security",
    },
    {
        "question_text": "Which of the following represents a strong password suggestion?",
        "option_a": "Password123!",
        "option_b": "admin1234",
        "option_c": "M@ster#92Secure!",
        "option_d": "Shreehari2005",
        "correct_answer": "C",
        "explanation": "M@ster#92Secure! has complexity: uppercase, lowercase, numbers, special characters, and is over 12 characters long.",
        "category": "password_security",
    },
    {
        "question_text": "Why should you use unique passwords for every separate account?",
        "option_a": "It speeds up browser login processes.",
        "option_b": "It prevents a database breach on one website from exposing credentials for all your other accounts.",
        "option_c": "It is required by hardware manufacturers.",
        "option_d": "Unique passwords compress local storage.",
        "correct_answer": "B",
        "explanation": "If you reuse passwords, a leak at one site allows hackers to hijack your email, bank, and social accounts through credential stuffing.",
        "category": "password_security",
    },
    {
        "question_text": "What is the primary risk of using security questions like 'What is your mother's maiden name?'?",
        "option_a": "They require double encryption.",
        "option_b": "The answers can often be easily found via social engineering or public profile research.",
        "option_c": "They slow down login servers.",
        "option_d": "They expire after 30 days.",
        "correct_answer": "B",
        "explanation": "Answers to standard security questions are often public or guessable. It's safer to treat answers as secondary passwords or generate fake answers.",
        "category": "password_security",
    },
    {
        "question_text": "What does a password strength meter evaluate?",
        "option_a": "The internet connection speed.",
        "option_b": "The entropy, length, and complexity of a typed password against dictionary patterns.",
        "option_c": "The age of the database server.",
        "option_d": "The resolution of your screen monitors.",
        "correct_answer": "B",
        "explanation": "Strength meters analyze password parameters to estimate how difficult the password would be to crack using automated dictionary tools.",
        "category": "password_security",
    },
    {
        "question_text": "What does Multi-Factor Authentication (MFA) provide?",
        "option_a": "A faster wireless internet speed.",
        "option_b": "An additional layer of security beyond passwords by requiring verification from a secondary device or biometric.",
        "option_c": "The ability to log in with multiple user accounts simultaneously.",
        "option_d": "A backup storage partition.",
        "correct_answer": "B",
        "explanation": "MFA ensures that even if an attacker steals your password, they cannot gain entry without the secondary factor (e.g. authenticator app code).",
        "category": "multi_factor_authentication",
    },
    {
        "question_text": "Which is the most secure factor for Two-Factor Authentication?",
        "option_a": "An authenticator app generating time-based one-time codes (TOTP).",
        "option_b": "Receiving codes via standard SMS text messages.",
        "option_c": "Writing passwords on notes next to screens.",
        "option_d": "Security questions with answers based on your public profile.",
        "correct_answer": "A",
        "explanation": "SMS codes can be intercepted via SIM-swapping or notifications on lockscreens. Authenticator apps operate locally and generate unique keys securely.",
        "category": "multi_factor_authentication",
    },
    {
        "question_text": "Is it safe to conduct online financial banking transactions on public Wi-Fi networks?",
        "option_a": "Yes, public Wi-Fi is secure because it has password controls.",
        "option_b": "No, public Wi-Fi traffic can be easily sniffed; use cellular data or a VPN.",
        "option_c": "Only during daytime business hours.",
        "option_d": "Yes, if your device browser is updated.",
        "correct_answer": "B",
        "explanation": "Public hotspots are open. Hackers can intercept data, execute MitM attacks, or spoof network portals. Use VPNs or mobile network data.",
        "category": "public_wifi",
    },
    {
        "question_text": "What does a Virtual Private Network (VPN) do when you use it?",
        "option_a": "It increases your cellular data limits.",
        "option_b": "It encrypts your device's traffic and routes it through a secure server.",
        "option_c": "It deletes your history from the local database.",
        "option_d": "It automatically blocks all malware files.",
        "correct_answer": "B",
        "explanation": "VPNs encrypt transmission packages, securing your session on public networks so hackers cannot spy on your credentials or files.",
        "category": "vpn",
    },
    {
        "question_text": "Under the Indian IT Act, 2000, what does Section 66C penalize?",
        "option_a": "Failure to install antivirus programs.",
        "option_b": "Identity theft using electronic signatures, passwords, or biometrics.",
        "option_c": "Sending commercial marketing advertisements.",
        "option_d": "Deleting old files from system trash bins.",
        "correct_answer": "B",
        "explanation": "Section 66C covers identity theft, making the fraudulent use of another person's login password or digital signature a punishable offense.",
        "category": "cyber_laws",
    },
    {
        "question_text": "What is the safest rule to follow regarding UPI payments in India?",
        "option_a": "Always enter your UPI PIN to check balance refunds.",
        "option_b": "Never enter your UPI PIN when receiving money; you only enter it when sending money.",
        "option_c": "Share your UPI PIN with customer support executives.",
        "option_d": "Scan QR codes sent by strangers on social networks.",
        "correct_answer": "B",
        "explanation": "Receiving payments via UPI requires no PIN entry. If a transaction asks for your UPI PIN, it is a payment FROM you. Never scan QR codes to receive money.",
        "category": "upi_fraud",
    },
    {
        "question_text": "What is a common sign of a QR code scam?",
        "option_a": "The QR code has a green outline.",
        "option_b": "A seller or stranger asks you to scan a QR code to 'receive a refund' or 'confirm payment'.",
        "option_c": "The QR code is printed on paper instead of a screen.",
        "option_d": "The code requires the Google Chrome browser.",
        "correct_answer": "B",
        "explanation": "Scammers overlay fraudulent QR codes on shop boards or send them via chat, claiming they are verification checks. Scanning them requests payments from your wallet.",
        "category": "upi_fraud",
    },
    {
        "question_text": "What security issue occurs during ARP cache poisoning?",
        "option_a": "Hard drive memory gets formatted.",
        "option_b": "Attackers link their MAC address with the IP address of the local gateway router.",
        "option_c": "Email attachment sizes are blocked.",
        "option_d": "Antivirus logs are deleted.",
        "correct_answer": "B",
        "explanation": "ARP poisoning maps the attacker's MAC to the local gateway IP, forcing all local network traffic to pass through their device first.",
        "category": "spoofing",
    },
    {
        "question_text": "Which of the following is the safest way to download software?",
        "option_a": "Download from search engine ads.",
        "option_b": "Directly from the developer's official verified website.",
        "option_c": "From peer-to-peer file sharing programs.",
        "option_d": "From forums that offer free registration cracks.",
        "correct_answer": "B",
        "explanation": "Software downloads from third-party sites frequently contain trojans. Always download from official channels and verify download hashes.",
        "category": "safe_downloads",
    },
    {
        "question_text": "What is a zero-day attack?",
        "option_a": "An attack that requires zero lines of code.",
        "option_b": "An exploit targeting a software bug before the vendor has released a security patch.",
        "option_c": "A network scan that completes in zero minutes.",
        "option_d": "An alert that has zero impact on firewalls.",
        "correct_answer": "B",
        "explanation": "Zero-day exploits occur because security researchers or vendors have had zero days to patch the newly discovered vulnerability.",
        "category": "hacking",
    },
    {
        "question_text": "What does Section 66D of the IT Act, 2000 cover in India?",
        "option_a": "Creating fake software update installers.",
        "option_b": "Cheating by personation using a communication device or computer resource.",
        "option_c": "Sharing secure passwords with coworkers.",
        "option_d": "Installing third-party web apps.",
        "correct_answer": "B",
        "explanation": "Section 66D penalizes phishing, identity theft, and profile spoofing where attackers masquerade as trusted entities online to defraud individuals.",
        "category": "cyber_laws",
    },
]


class Command(BaseCommand):
    help = 'Seeds database with exactly 390 targeted cybersecurity questions focusing on Phishing, Malware, Hacking, Spoofing, Cyberbullying, and Defamation.'

    def handle(self, *args, **options):
        # 1. Clean out existing questions
        Question.objects.all().delete()
        self.stdout.write(self.style.WARNING('Cleared existing questions from database.'))

        # 2. Seed badges
        self.seed_badges()

        # 3. Seed targeted templates
        user_types = ['student', 'professional', 'public']
        difficulties = ['easy', 'medium', 'hard']

        created = 0
        for idx, tpl in enumerate(TEMPLATES):
            # Seed each template for the three user types to ensure complete coverage.
            # We vary the difficulty and assign it logically so it is diverse.
            for ut_idx, ut in enumerate(user_types):
                diff = difficulties[(idx + ut_idx) % 3]
                Question.objects.create(
                    question_text=tpl["question_text"],
                    option_a=tpl["option_a"],
                    option_b=tpl["option_b"],
                    option_c=tpl["option_c"],
                    option_d=tpl["option_d"],
                    correct_answer=tpl["correct_answer"],
                    explanation=tpl["explanation"],
                    category=tpl["category"],
                    difficulty=diff,
                    target_user_type=ut,
                )
                created += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} questions (Target: 350 - 400).'))

    def seed_badges(self):
        """Create achievement badges if they don't exist."""
        badges_data = [
            {
                'name': 'First Steps',
                'description': 'Complete your first quiz',
                'icon': '🎯',
                'criteria_type': 'first_quiz',
                'criteria_value': 1,
            },
            {
                'name': 'Perfect Score',
                'description': 'Score 100% on a quiz',
                'icon': '🏆',
                'criteria_type': 'perfect_score',
                'criteria_value': 100,
            },
            {
                'name': 'Cyber Guardian',
                'description': 'Score above 80% on a quiz',
                'icon': '🛡️',
                'criteria_type': 'score_above_80',
                'criteria_value': 80,
            },
            {
                'name': 'Dedicated Learner',
                'description': 'Complete 5 quizzes',
                'icon': '📚',
                'criteria_type': 'attempts_5',
                'criteria_value': 5,
            },
            {
                'name': 'Quiz Master',
                'description': 'Complete 10 quizzes',
                'icon': '🎓',
                'criteria_type': 'attempts_10',
                'criteria_value': 10,
            },
            {
                'name': 'Phishing Expert',
                'description': 'Score 90%+ on phishing questions',
                'icon': '🎣',
                'criteria_type': 'phishing_expert',
                'criteria_value': 90,
            },
            {
                'name': 'Malware Hunter',
                'description': 'Score 90%+ on malware questions',
                'icon': '🦠',
                'criteria_type': 'malware_expert',
                'criteria_value': 90,
            },
            {
                'name': 'Speed Demon',
                'description': 'Complete a quiz in under half the allowed time',
                'icon': '⚡',
                'criteria_type': 'speed_demon',
                'criteria_value': 0,
            },
            {
                'name': 'Consistent Performer',
                'description': 'Score above 70% on 3 or more quizzes',
                'icon': '📈',
                'criteria_type': 'consistent',
                'criteria_value': 3,
            },
            {
                'name': 'Rising Star',
                'description': 'Improve your score by 20%+ from your first attempt',
                'icon': '⭐',
                'criteria_type': 'improved',
                'criteria_value': 20,
            },
        ]

        created_count = 0
        for badge_data in badges_data:
            _, created = Badge.objects.get_or_create(
                criteria_type=badge_data['criteria_type'],
                defaults=badge_data,
            )
            if created:
                created_count += 1
        self.stdout.write(f'Verified badges (total: {Badge.objects.count()}).')
