# Generated by Django 4.2.30 on 2026-06-11 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('criteria_type', models.CharField(choices=[('first_quiz', 'Complete First Quiz'), ('perfect_score', 'Score 100%'), ('score_above_80', 'Score Above 80%'), ('attempts_5', 'Complete 5 Quizzes'), ('attempts_10', 'Complete 10 Quizzes'), ('phishing_expert', 'Score 90%+ on Phishing'), ('malware_expert', 'Score 90%+ on Malware'), ('speed_demon', 'Complete in Under Half Time'), ('consistent', '3 Scores Above 70%'), ('improved', 'Improve Score by 20%+')], max_length=50, unique=True)),
                ('criteria_value', models.IntegerField(default=0, help_text='Threshold value for the criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='leaderboard.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
