# Generated by Django 4.2.30 on 2026-07-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_personalized',
            field=models.BooleanField(default=False, help_text='Generated for survey-based personalization'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('password_security', 'Password Security'), ('phishing', 'Phishing'), ('malware', 'Malware'), ('ransomware', 'Ransomware'), ('spyware', 'Spyware'), ('adware', 'Adware'), ('trojans', 'Trojans'), ('worms', 'Worms'), ('viruses', 'Viruses'), ('social_engineering', 'Social Engineering'), ('cyber_bullying', 'Cyber Bullying'), ('spoofing', 'Spoofing'), ('identity_theft', 'Identity Theft'), ('data_privacy', 'Data Privacy'), ('encryption', 'Encryption'), ('authentication', 'Authentication'), ('multi_factor_authentication', 'Multi-Factor Authentication'), ('public_wifi', 'Public Wi-Fi'), ('vpn', 'VPN'), ('cloud_security', 'Cloud Security'), ('browser_security', 'Browser Security'), ('safe_downloads', 'Safe Downloads'), ('digital_footprint', 'Digital Footprint'), ('mobile_security', 'Mobile Security'), ('banking_fraud', 'Banking Fraud'), ('upi_fraud', 'UPI Fraud'), ('qr_code_scam', 'QR Code Scam'), ('fake_apps', 'Fake Apps'), ('fake_websites', 'Fake Websites'), ('ai_scams', 'AI Scams'), ('deepfake', 'Deepfake'), ('online_shopping_fraud', 'Online Shopping Fraud'), ('email_security', 'Email Security'), ('insider_threats', 'Insider Threats'), ('iot_security', 'IoT Security'), ('network_security', 'Network Security'), ('cyber_laws', 'Cyber Laws'), ('cyber_ethics', 'Cyber Ethics'), ('safe_social_media', 'Safe Social Media Practices')], default='phishing', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz_type',
            field=models.CharField(choices=[('20', '20 Questions - 30 Minutes'), ('30', '30 Questions - 40 Minutes'), ('50', '50 Questions - 50 Minutes')], default='20', max_length=10),
        ),
    ]
